web:
  image: 922560784203.dkr.ecr.us-east-1.amazonaws.com/console-private:20180724
  ports:
    - 443:5000
  labels:
    - convox.cron.backup=0 4 * * ? backup
    - convox.cron.cleanupjobs=30 * * * ? cleanup-jobs
    - convox.cron.pingracks=22 * * * ? pingracks
    - convox.port.443.protocol=tls
    - convox.port.443.secure=true
    - convox.port.443.proxy=true
  mem_limit: 512MB
  env:
    ALLOW_SIGNUP=false
    TABLE_PREFIX=console-private
workers:
  image: 922560784203.dkr.ecr.us-east-1.amazonaws.com/console-private:20180724
  mem_limit: 512MB
